/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiResumeResumeIdPdfRouteImport } from './routes/api/resume.$resumeId.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeResumeIdPdfRoute = ApiResumeResumeIdPdfRouteImport.update({
  id: '/api/resume/$resumeId/pdf',
  path: '/api/resume/$resumeId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/resume/$resumeId/pdf': typeof ApiResumeResumeIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/resume/$resumeId/pdf': typeof ApiResumeResumeIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/resume/$resumeId/pdf': typeof ApiResumeResumeIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/resume/$resumeId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/resume/$resumeId/pdf'
  id: '__root__' | '/' | '/api/resume/$resumeId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiResumeResumeIdPdfRoute: typeof ApiResumeResumeIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume/$resumeId/pdf': {
      id: '/api/resume/$resumeId/pdf'
      path: '/api/resume/$resumeId/pdf'
      fullPath: '/api/resume/$resumeId/pdf'
      preLoaderRoute: typeof ApiResumeResumeIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiResumeResumeIdPdfRoute: ApiResumeResumeIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
